# Deep Learning - ANNs

## Importing Libraries

In [2]:
!pip install tensorflow

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [6]:
df = pd.read_csv('Churn_Modelling.csv')
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding the categorical data

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [10]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### One Hot Encoding the Geography Column

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into training and test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

### Feature Scaling
    Very fundamental for deep learning

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

### Adding the Input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #6 is random enough
#choosing rectilinear filter for activation fun

### Adding the second hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # same as first hidden layer, change could improve also.

### Adding the output layer

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

output layer filter is fixed with sigmoid function<br>
fixing sigmoid function enables to produce the probability of a certain result occuring becuz of the functions continuity

## Part 3 - Training the ANN

### Compiling the ANN

In [22]:
ann.compile(optimizer ='adam', loss ='binary_crossentropy', metrics =['accuracy'])

### Training the ANN on the training set

In [23]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 4s 4ms/step - loss: 0.5306 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4953 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4770 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4586 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4495 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4448 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4410 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4379 - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4354 - accuracy: 0.7960
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4327 - accura

## Part 4 - Making predictions and model evaluation

### Predicting a single evaluation

In [26]:
print(ann.predict(sc.transform([[1.0,1.0,1.0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 98ms/step
[[False]]


Customer wont leave the bank

### Predicting the test set results

In [28]:
y_pred= ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 6ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the confusion matrix

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1477  118]
 [ 170  235]]


0.856